import { useEffect, useRef, useState } from 'react';
import { BookOpen, FolderOpen, Search, Settings2, PanelLeftClose, PanelLeftOpen, Highlighter, Underline, PenLine, MousePointer2, MessageSquare, Save, Undo2, Redo2, Minus, Plus, ChevronLeft, ChevronRight, Link2, Unlink, Download, X, FileText, Check, LoaderCircle, Trash2, List, ArrowUpRight, Pause, Sun, Moon, HardDrive, Cloud } from 'lucide-react';
import { Reader, type ReaderHandle } from './Reader';
import type { Mark, Match, Settings, Side, State, Tool } from './types';

const initial: State = { doc:null,settings:{provider:'local',baseUrl:'https://api.deepseek.com',model:'deepseek-flash',autoTranslate:true,hasKey:false},recent:[],canUndo:false,canRedo:false,queued:0,translating:false };
const names: Record<string,string> = { highlight:'高亮',underline:'下划线',ink:'手绘',note:'批注' };
const accuracy: Record<string,string> = {pending:'等待译文后对应',unmatched:'未找到对应文本',paragraph:'近似对应 · 整段',phrase:'短语对应 · 近似',position:'按页面位置同步'};
const colors = ['#edba39','#57b995','#7899e6','#e98eaa'];
function Logo(){return <div className="brand-symbol"><i/><i/><i/></div>;}
function Action({label,children,onClick,disabled,active,className=''}:{label:string;children:React.ReactNode;onClick?:()=>void;disabled?:boolean;active?:boolean;className?:string}){return <button title={label} aria-label={label} disabled={disabled} onClick={onClick} className={`icon-button ${active?'selected':''} ${className}`}>{children}</button>;}

export default function App(){
  const [theme,setTheme]=useState<'light'|'dark'>(()=>localStorage.getItem('theme')==='dark'?'dark':'light');
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme);},[theme]);
  const [state,setState]=useState<State>(initial),[tool,setTool]=useState<Tool>('select'),[color,setColor]=useState(colors[0]),[zoomState,setZoomState]=useState({source:'',value:1}),[synced,setSynced]=useState(true),[page,setPage]=useState(0),[pageInput,setPageInput]=useState('1');
  const [panel,setPanel]=useState<'outline'|'annotations'|'search'|null>('outline'),[settingsOpen,setSettingsOpen]=useState(false),[selected,setSelected]=useState<string|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[exportOpen,setExportOpen]=useState(false);
  const [query,setQuery]=useState(''),[matches,setMatches]=useState<Match[]>([]),[searching,setSearching]=useState(false);
  const left=useRef<ReaderHandle>(null),right=useRef<ReaderHandle>(null),pageTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),searchId=useRef(0),noticeTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const doc=state.doc,mark=doc?.annotations.find(a=>a.id===selected);
  const reading=useRef<{documentUrl:string;page:number;fraction:number;zoom:number}|null>(null);
  if(doc&&reading.current?.documentUrl!==doc.sourceUrl)reading.current={documentUrl:doc.sourceUrl,page:doc.currentPage,fraction:doc.currentFraction,zoom:doc.viewZoom};
  const zoom=doc&&zoomState.source===doc.sourceUrl?zoomState.value:doc?.viewZoom??1;
  async function call<T=unknown>(action:string,args?:unknown):Promise<T|undefined>{try{return await window.pdfsandwich.call<T>(action,args);}catch(e){setError((e as Error).message.replace(/^Error invoking remote method '[^']+': Error: /,''));}}
  const notify=(message:string)=>{setNotice(message);clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),6000);};
  useEffect(()=>{void window.pdfsandwich.call<State>('state').then(setState);return window.pdfsandwich.onState(setState);},[]);
  useEffect(()=>{clearTimeout(pageTimer.current);if(doc){setPage(doc.currentPage);setPageInput(String(doc.currentPage+1));setSelected(null);setMatches([]);setSearching(false);searchId.current++;void call('page',reading.current);}},[doc?.sourceUrl]);
  useEffect(()=>setPageInput(String(page+1)),[page]);
  function rememberReading(){clearTimeout(pageTimer.current);const position=reading.current;pageTimer.current=setTimeout(()=>void call('page',position),250);}
  const open=async(path?:string)=>{setBusy('正在读取文档…');clearTimeout(pageTimer.current);if(reading.current)await call('page',reading.current);await call('open',{path});setBusy('');};
  const save=async()=>{setBusy('正在保存批注…');const result=await call<{backup:string}>('save');setBusy('');if(result)notify('批注已保存到原 PDF，原文件备份已创建。');};
  function position(side:Side,next:number,fraction:number){if(!reading.current)return;setPage(next);if(synced)(side==='en'?right:left).current?.go(next,fraction);reading.current={...reading.current,page:next,fraction};rememberReading();}
  function go(next:number){if(!doc||!reading.current)return;clearTimeout(pageTimer.current);next=Math.max(0,Math.min(doc.pages.length-1,next));setPage(next);left.current?.go(next);right.current?.go(next);reading.current={...reading.current,page:next,fraction:0};void call('page',reading.current);}
  function changeZoom(update:(value:number)=>number,x=.5,y=.5){if(!doc||!reading.current)return;const value=Math.max(.5,Math.min(3,Math.round(update(reading.current.zoom)*1000)/1000));if(value===reading.current.zoom)return;left.current?.captureZoomAnchor(x,y);right.current?.captureZoomAnchor(x,y);reading.current={...reading.current,zoom:value};setZoomState({source:doc.sourceUrl,value});rememberReading();}
  function selectMark(id:string){setSelected(id);setPanel('annotations');const item=doc?.annotations.find(m=>m.id===id);if(item)go(item.page);}
  async function addMark(item:Mark){await call('annotate',{item});if(item.kind==='note'){setSelected(item.id);setPanel('annotations');}}
  async function search(){const id=++searchId.current;if(!query.trim()||!doc)return;setSearching(true);setMatches([]);let start:number|null=0;let found:Match[]=[];while(start!==null&&id===searchId.current){const result:{matches:Match[];next:number|null}|undefined=await call('search',{query:query.trim(),start});if(!result)break;if(id!==searchId.current)return;found=[...found,...result.matches];setMatches(found);start=result.next;}if(id===searchId.current)setSearching(false);}
  useEffect(()=>{const key=(e:KeyboardEvent)=>{
    const editing=['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName);
    if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='o'){e.preventDefault();void open();}else if(e.key.toLowerCase()==='s'){e.preventDefault();void save();}else if(e.key.toLowerCase()==='f'){e.preventDefault();setPanel('search');}else if(e.key.toLowerCase()==='z'&&!editing){e.preventDefault();void call(e.shiftKey?'redo':'undo');}else if(e.key==='+'||e.key==='='){e.preventDefault();changeZoom(z=>z+.1);}else if(e.key==='-'){e.preventDefault();changeZoom(z=>z-.1);}else if(e.key==='0'){e.preventDefault();changeZoom(()=>1);}}
    else if(!editing){if(e.key==='Escape'){setSelected(null);setSettingsOpen(false);setTool('select');}if(e.key==='ArrowRight')go(page+1);if(e.key==='ArrowLeft')go(page-1);}
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[doc,page]);
  const ready=doc?Object.values(doc.translations).filter(p=>p.status==='ready').length:0;
  const tools:[Tool,React.ReactNode,string][]=[['select',<MousePointer2 size={17}/>,'选择文字'],['highlight',<Highlighter size={17}/>,'高亮文字'],['underline',<Underline size={17}/>,'下划线'],['ink',<PenLine size={17}/>,'手绘记号'],['note',<MessageSquare size={17}/>,'添加批注']];
  return <div className="app" onDragOver={e=>{e.preventDefault();}} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void open(window.pdfsandwich.pathForFile(file));}}>
    <header className="app-header"><div className="brand"><Logo/><div><strong>PDFSandwich</strong><span>中英对照 · 专注阅读</span></div></div><div className="header-document">{doc?<><FileText size={16}/><span title={doc.path}>{doc.name}</span>{doc.dirty&&<i className="unsaved-dot" title="有未写入 PDF 的批注"/>}</>:<span className="header-hint">让理解，发生在两页之间。</span>}</div><button className="button secondary compact" onClick={()=>void open()}><FolderOpen size={16}/>打开 PDF</button><Action label={theme==='light'?'切换深色主题':'切换浅色主题'} onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</Action><Action label="翻译与应用设置" onClick={()=>setSettingsOpen(true)}><Settings2 size={19}/></Action></header>
    <div className="toolbar"><div className="toolbar-group"><Action label="显示或隐藏侧栏" active={!!panel} onClick={()=>setPanel(panel?null:'outline')}>{panel?<PanelLeftClose size={17}/>:<PanelLeftOpen size={17}/>}</Action><Action label="全文搜索 Ctrl+F" active={panel==='search'} disabled={!doc} onClick={()=>setPanel('search')}><Search size={17}/></Action></div><div className="toolbar-group tools">{tools.map(([id,icon,label])=><Action key={id} label={label} active={tool===id} disabled={!doc} onClick={()=>setTool(id)}>{icon}</Action>)}<span className="color-divider"/>{colors.map(c=><button key={c} aria-label={`标记颜色 ${c}`} title="标记颜色" className={`color-dot ${c===color?'chosen':''}`} style={{background:c}} onClick={()=>setColor(c)}/>)}</div><div className="toolbar-group"><Action label="撤销 Ctrl+Z" disabled={!state.canUndo} onClick={()=>void call('undo')}><Undo2 size={16}/></Action><Action label="重做 Ctrl+Shift+Z" disabled={!state.canRedo} onClick={()=>void call('redo')}><Redo2 size={16}/></Action></div><div className="toolbar-spacer"/><div className="toolbar-group zoom-controls"><Action label="缩小 Ctrl+-" disabled={!doc} onClick={()=>changeZoom(z=>z-.1)}><Minus size={16}/></Action><button className="zoom-value" disabled={!doc} title="恢复适合页宽 Ctrl+0" onClick={()=>changeZoom(()=>1)}>{zoom===1?'适合页宽':`${Math.round(zoom*100)}%`}</button><Action label="放大 Ctrl++" disabled={!doc} onClick={()=>changeZoom(z=>z+.1)}><Plus size={16}/></Action></div><button className="button save-button" disabled={!doc?.dirty||!!busy} onClick={()=>void save()}><Save size={15}/>保存原 PDF</button></div>
    {!doc?<main className="welcome"><div className="welcome-copy"><div className="eyebrow"><span/> YOUR BILINGUAL READING DESK</div><h1>读懂每一页，<br/><em>保留每个想法。</em></h1><p>英文原文与中文译文并肩呈现。<br/>从一篇论文到一本教材，让阅读与思考同步。</p><button className="button primary large" onClick={()=>void open()}><FolderOpen size={19}/>打开英文 PDF <span>Ctrl O</span></button><small>也可以将 PDF 文件拖到这里</small><div className="welcome-features"><span><Link2 size={15}/>双栏同步</span><span><PenLine size={15}/>双向批注</span><span><BookOpen size={15}/>保留版式</span></div></div><div className="welcome-art" aria-hidden="true"><div className="paper-art paper-back"><div className="paper-tag">ENGLISH</div><h3>The art of<br/>understanding.</h3><div className="fake-rule wide"/><div className="fake-rule"/><div className="fake-rule wide"/><div className="fake-highlight"/><div className="fake-rule wide"/><div className="formula">E = mc²</div><div className="fake-rule"/><div className="fake-rule wide"/><small>01 / ORIGINAL</small></div><div className="paper-art paper-front"><div className="paper-tag teal">简体中文</div><h3>理解的艺术，<br/>思考的空间。</h3><div className="fake-rule wide"/><div className="fake-rule"/><div className="fake-highlight"/><div className="fake-rule wide"/><div className="formula">E = mc²</div><div className="fake-rule"/><div className="fake-rule wide"/><small>01 / TRANSLATION</small></div><div className="floating-sync"><Link2 size={18}/><span>同一份思考，两种语言</span></div></div>{state.recent.length>0&&<section className="recent"><div className="section-heading"><h2>继续阅读</h2><span>最近打开</span></div><div className="recent-list">{state.recent.slice(0,4).map(item=><button key={item.path} onClick={()=>void open(item.path)}><div className="recent-icon"><FileText size={21}/></div><div><strong>{item.name}</strong><span>{item.pages} 页 · {new Date(item.openedAt).toLocaleDateString('zh-CN')}</span></div><ArrowUpRight size={17}/></button>)}</div></section>}</main>:<main className="workspace">
      {panel&&<aside className="sidebar"><div className="sidebar-tabs"><button className={panel==='outline'?'active':''} onClick={()=>setPanel('outline')}><List size={15}/>目录</button><button className={panel==='annotations'?'active':''} onClick={()=>setPanel('annotations')}><MessageSquare size={15}/>批注 <b>{doc.annotations.length}</b></button><Action label="关闭侧栏" onClick={()=>setPanel(null)}><X size={15}/></Action></div><div className="sidebar-content">
        {panel==='outline'&&<><div className="document-card"><div className="small-eyebrow">当前文档</div><strong>{doc.name}</strong><span>{doc.pages.length} 页 · {(doc.size/1048576).toFixed(1)} MB</span></div><div className="small-eyebrow section-label">文档目录</div>{doc.outline.length?doc.outline.map(([level,title,p],i)=><button key={i} className={`outline-row ${p===page+1?'current':''}`} style={{paddingLeft:12+Math.min(level-1,4)*12}} onClick={()=>go(p-1)}><span>{title}</span><small>{p}</small></button>):<div className="sidebar-empty"><List size={25}/><p>这份 PDF 没有内置目录</p><small>使用底部页码或搜索快速定位</small></div>}</>}
        {panel==='annotations'&&<><div className="small-eyebrow section-label">所有标记与想法</div>{doc.annotations.length?doc.annotations.map(item=><button key={item.id} className={`annotation-card ${selected===item.id?'active':''}`} onClick={()=>selectMark(item.id)}><div><i style={{background:item.color}}/><strong>{names[item.kind]}</strong><span>第 {item.page+1} 页</span></div><p>{item.content||item.selectedText||'点击查看或添加批注'}</p><small>{accuracy[item.accuracy]||item.accuracy}</small></button>):<div className="sidebar-empty"><PenLine size={25}/><p>给值得记住的内容留个标记</p><small>选择顶部工具，在任一侧进行批注</small></div>}</>}
        {panel==='search'&&<><form className="search-box" onSubmit={e=>{e.preventDefault();void search();}}><Search size={16}/><input autoFocus aria-label="搜索 PDF 原文" placeholder="搜索英文原文…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" title="开始搜索"><ChevronRight size={17}/></button></form><div className="search-summary">{searching?<><LoaderCircle size={13} className="spin"/> 正在逐批搜索…</>:`${matches.length} 个匹配页面`}</div>{matches.map(item=><button key={item.page} className="search-result" onClick={()=>go(item.page)}><span>第 {item.page+1} 页 · {item.rects.length} 处</span><p>{item.text}</p></button>)}</>}
      </div><div className="sidebar-bottom"><div><span>中文翻译</span><strong>{ready} / {doc.pages.length} 页</strong></div><div className="progress-track"><i style={{width:`${ready/doc.pages.length*100}%`}}/></div><small>{state.translating?`正在翻译 · 队列剩余 ${state.queued} 页`:'翻译结果缓存在本机'}</small></div></aside>}
      <section className="reading-desk"><div className="pane-headings"><div><span className="language-badge">EN</span><strong>英文原文</strong><small>Original</small></div><button className={`sync-toggle ${synced?'active':''}`} onClick={()=>{setSynced(!synced);if(!synced)go(page);}} title="切换左右同步滚动">{synced?<Link2 size={15}/>:<Unlink size={15}/>} {synced?'同步阅读':'独立阅读'}</button><div><span className="language-badge zh">中</span><strong>中文译文</strong><small>Translation</small><div className="translation-actions">{state.translating?<Action label="暂停翻译队列" onClick={()=>void call('stop')}><Pause size={15}/></Action>:<button onClick={()=>void call('translate',{all:true})}>翻译整本</button>}<div className="export-wrap"><Action label="导出译文" onClick={()=>setExportOpen(!exportOpen)}><Download size={16}/></Action>{exportOpen&&<div className="dropdown"><button onClick={()=>{setExportOpen(false);void call('export',{mode:'chinese'});}}>导出中文 PDF</button><button onClick={()=>{setExportOpen(false);void call('export',{mode:'bilingual'});}}>导出中英交替页 PDF</button></div>}</div></div></div></div><div className="reader-columns">{(['en','zh'] as Side[]).map(side=><Reader key={side} ref={side==='en'?left:right} doc={doc} side={side} zoom={zoom} tool={tool} color={color} marks={doc.annotations} matches={matches} onPosition={(p,f)=>position(side,p,f)} onWheelZoom={(factor,x,y)=>changeZoom(value=>value*factor,x,y)} onMark={item=>void addMark(item)} onSelectMark={selectMark} onTranslate={p=>void call('translate',{page:p})} onError={setError}/>)}</div><footer className="reader-footer"><div className="save-status">{doc.dirty?<><span className="status-dot amber"/>草稿已保存 · Ctrl+S 写入原 PDF</>:<><Check size={13}/>批注已写入原 PDF</>}</div><div className="page-controls"><Action label="上一页" disabled={page===0} onClick={()=>go(page-1)}><ChevronLeft size={16}/></Action><form onSubmit={e=>{e.preventDefault();const n=Number(pageInput);if(Number.isInteger(n))go(n-1);}}><input aria-label="当前页码" value={pageInput} onChange={e=>setPageInput(e.target.value)} onBlur={()=>setPageInput(String(page+1))}/><span>/ {doc.pages.length}</span></form><Action label="下一页" disabled={page===doc.pages.length-1} onClick={()=>go(page+1)}><ChevronRight size={16}/></Action></div><div className="footer-right"><span className="status-dot"/>{state.settings.provider==='local'?'本地翻译 · 无需 API':state.settings.model}</div></footer></section>
    </main>}
    {mark&&<div className="note-editor"><div className="note-editor-title"><span><i style={{background:mark.color}}/>{names[mark.kind]} · 第 {mark.page+1} 页</span><Action label="关闭批注编辑" onClick={()=>setSelected(null)}><X size={16}/></Action></div>{mark.selectedText&&<blockquote>{mark.selectedText}</blockquote>}<textarea key={mark.id} autoFocus={mark.kind==='note'} aria-label="批注内容" placeholder="写下你的想法…" defaultValue={mark.content} onBlur={e=>{if(e.target.value!==mark.content)void call('editAnnotation',{id:mark.id,content:e.target.value});}}/><div className="note-editor-bottom"><span>{accuracy[mark.accuracy]}</span><Action label="删除此标记" onClick={()=>{void call('editAnnotation',{id:mark.id,remove:true});setSelected(null);}}><Trash2 size={15}/></Action></div></div>}
    {settingsOpen&&<SettingsDialog settings={state.settings} onClose={()=>setSettingsOpen(false)} onSave={async(value)=>{const result=await window.pdfsandwich.call<Settings>('settings',value);notify('翻译设置已保存');return result;}} onTest={()=>window.pdfsandwich.call<{text:string}>('testConnection')}/>}
    {notice&&<div className="toast"><Check size={17}/>{notice}</div>}{error&&<div className="error-banner" role="alert"><span>{error}</span><Action label="关闭错误提示" onClick={()=>setError('')}><X size={16}/></Action></div>}{busy&&<div className="busy-overlay"><LoaderCircle className="spin" size={22}/><span>{busy}</span></div>}
  </div>;
}

function SettingsDialog({settings,onClose,onSave,onTest}:{settings:Settings;onClose:()=>void;onSave:(value:unknown)=>Promise<Settings>;onTest:()=>Promise<{text:string}>}){
  const [form,setForm]=useState({...settings,key:''}),[working,setWorking]=useState(false),[result,setResult]=useState(''),[error,setError]=useState('');
  async function submit(test=false){setWorking(true);setError('');setResult('');try{const saved=await onSave(form);setForm({...saved,key:''});if(test){const answer=await onTest();setResult(answer.text);}else onClose();}catch(e){setError((e as Error).message);}finally{setWorking(false);}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!working)onClose();}}>
    <section className="settings-modal" role="dialog" aria-label="翻译设置">
      <div className="modal-title"><div><div className="small-eyebrow">YOUR READING PREFERENCES</div><h2>翻译设置</h2></div><Action label="关闭设置" onClick={onClose}><X size={20}/></Action></div>
      <p className="modal-description">选择适合你的翻译方式。两种方式都保留页面中的公式与图片。</p>
      <div className="provider-cards">
        <button className={form.provider==='local'?'active':''} onClick={()=>setForm({...form,provider:'local'})}><HardDrive size={21}/><strong>本地开源翻译</strong><span>离线运行 · 无按量费用</span>{form.provider==='local'&&<Check size={15}/>}</button>
        <button className={form.provider==='api'?'active':''} onClick={()=>setForm({...form,provider:'api'})}><Cloud size={21}/><strong>云端 API</strong><span>自选服务 · 按服务计费</span>{form.provider==='api'&&<Check size={15}/>}</button>
      </div>
      {form.provider==='local'?<div className="local-model-card"><div><span className="status-dot"/><strong>Argos 英语 → 简体中文</strong><span className="pill">开源模型</span></div><p>首次翻译会下载语言模型、排版模型和字体，合计约 400 MB。下载完成后可离线使用，文档文字留在这台电脑。</p><small>适合日常阅读。复杂学术术语和长句建议对照原文确认；也可切换到更高质量的云端模型。</small></div>:<>
        <div className="provider-buttons"><button className={form.baseUrl.includes('deepseek')?'active':''} onClick={()=>setForm({...form,baseUrl:'https://api.deepseek.com',model:'deepseek-flash',key:''})}>DeepSeek</button><button className={form.baseUrl.includes('localhost')?'active':''} onClick={()=>setForm({...form,baseUrl:'http://localhost:11434/v1',model:'qwen3:8b',key:'local'})}>本地 Ollama</button><span>兼容 OpenAI 接口</span></div>
        <label>服务地址<input value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})} placeholder="https://api.deepseek.com"/></label>
        <label>模型名称<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} placeholder="填写服务提供的模型 ID"/></label>
        <label>API Key <span>{form.hasKey?'已保存 · 留空保留现有密钥':'仅保存在这台电脑'}</span><input type="password" value={form.key} onChange={e=>setForm({...form,key:e.target.value})} placeholder={form.hasKey?'••••••••••••••••':'输入 API Key'} autoComplete="off"/></label>
        <p className="privacy-caption">选择云端服务后，待翻译的正文会发送至该服务。</p>
      </>}
      <label className="checkbox-label"><input type="checkbox" checked={form.autoTranslate} onChange={e=>setForm({...form,autoTranslate:e.target.checked})}/><div><strong>随阅读自动翻译</strong><small>优先当前页与相邻页面，已完成的页面会缓存。{form.provider==='api'?'会使用你的 API 额度。':''}</small></div></label>
      <div className="settings-note"><BookOpen size={18}/><span>针对可选中文字的 PDF，不启用 OCR。译文与原文按页同步，批注文字保持原样。</span></div>
      {result&&<div className="connection-result">{result}</div>}{error&&<div className="connection-error">{error}</div>}
      <div className="modal-actions">{form.provider==='api'?<button className="button secondary" disabled={working} onClick={()=>void submit(true)}>{working?<LoaderCircle size={15} className="spin"/>:<Link2 size={15}/>}保存并测试连接</button>:<span className="local-footer"><HardDrive size={15}/> 在你的电脑上运行</span>}<button className="button primary" disabled={working} onClick={()=>void submit()}>保存设置</button></div>
    </section>
  </div>;
}
