import { useEffect,useState } from 'react';
import { X,Search,LoaderCircle,Check,Copy } from 'lucide-react';
import { api,errorText } from './research-types';
import type { LibraryDocument,LibraryState } from './types';
type Candidate={title:string;authors:string;year:string;doi:string;abstract:string;journal:string;bibtex:string;url:string;provider:string};
export function MetadataDialog({item,onClose,onApply}:{item:LibraryDocument;onClose:()=>void;onApply:(state:LibraryState)=>void}){
  const [query,setQuery]=useState(item.doi||item.title),[results,setResults]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[fields,setFields]=useState(['title','authors','year','doi','abstract','journal','url','bibtex']);
  useEffect(()=>{let alive=true;void api<{doi:string;arxiv:string;title:string}>('metadataIdentify',{id:item.id}).then(value=>{if(alive)setQuery(item.doi||value.doi||value.arxiv||value.title||item.title);}).catch(()=>{});return()=>{alive=false;};},[item.id]);
  async function search(){setBusy(true);setError('');setSelected(null);try{const result=await api<Candidate[]>('metadataLookup',{query});setResults(result);if(!result.length)setError('没有检索到匹配文献，可尝试 DOI 或完整标题。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function apply(){if(!selected)return;setBusy(true);try{const result=await api<LibraryState>('metadataApply',{id:item.id,changes:Object.fromEntries(fields.map(k=>[k,selected[k as keyof Candidate]]))});onApply(result);onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="metadata-dialog" role="dialog" aria-label="检索文献元数据"><div className="modal-title"><h2>检索文献元数据</h2><button className="icon-button" aria-label="关闭元数据" onClick={onClose}><X size={20}/></button></div><form className="metadata-query" onSubmit={e=>{e.preventDefault();void search();}}><input aria-label="DOI 或文献标题" value={query} onChange={e=>setQuery(e.target.value)} placeholder="DOI / arXiv ID / 文献标题"/><button className="button primary" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Search size={16}/>}检索</button></form><p className="muted">只向 Crossref 或 arXiv 发送检索词。核对候选后，选择需要更新的字段。</p><div className="metadata-results">{results.map((r,i)=><button key={i} className={selected===r?'active':''} onClick={()=>setSelected(r)}><strong>{r.title}</strong><span>{r.authors}</span><small>{r.year} · {r.journal} · {r.provider}</small></button>)}</div>{selected&&<><div className="metadata-fields">{[['title','标题'],['authors','作者'],['year','年份'],['doi','DOI'],['abstract','摘要'],['journal','期刊 / 会议'],['url','链接'],['bibtex','BibTeX']].map(([key,label])=><label key={key}><input type="checkbox" checked={fields.includes(key)} onChange={e=>setFields(e.target.checked?[...fields,key]:fields.filter(f=>f!==key))}/>{label}</label>)}</div><textarea aria-label="BibTeX 预览" className="bibtex-preview" readOnly rows={6} value={selected.bibtex}/><button className="button secondary" onClick={()=>void api('researchCopy',{text:selected.bibtex}).then(()=>setCopied(true))}><Copy size={14}/>{copied?'已复制':'复制 BibTeX'}</button></>}{error&&<p className="research-error">{error}</p>}<div className="modal-actions"><span/ ><button className="button primary" disabled={!selected||busy||!fields.length} onClick={()=>void apply()}><Check size={16}/>更新所选字段</button></div></section></div>;
}
