import { useEffect, useState } from 'react';
import { X,NotebookPen,Copy,LoaderCircle,ScanText } from 'lucide-react';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import { api,errorText,type Excerpt,type Capture } from './research-types';

export function ExcerptDialog({excerpts,capture,formula,onClose,onSaved}:{excerpts:Excerpt[];capture?:Capture;formula?:boolean;onClose:()=>void;onSaved:(id:string)=>void}){
  const [bilingual,setBilingual]=useState(true),[thought,setThought]=useState(''),[latex,setLatex]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(''),[copied,setCopied]=useState(''),[attempt,setAttempt]=useState(0),[recognizing,setRecognizing]=useState(!!formula),[recognized,setRecognized]=useState(false);
  useEffect(()=>{
    if(!formula||!capture)return;
    let active=true;setRecognizing(true);setRecognized(false);setError('');setLatex('');setCopied('');
    void api<{latex:string}>('formulaRecognize',{clipId:capture.id,retry:attempt>0}).then(result=>{if(active){setLatex(result.latex);setRecognized(true);}}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setRecognizing(false);});
    return()=>{active=false;};
  },[formula,capture?.id,attempt]);
  let preview='';try{if(latex)preview=katex.renderToString(latex,{displayMode:true,throwOnError:false,trust:false});}catch{}
  async function copy(markdown=false){await api('researchCopy',{text:markdown?`$$\n${latex}\n$$`:latex});setCopied('已复制');}
  async function save(){setBusy('正在保存摘录…');try{const result=await api<{excerptId:string;duplicate:boolean}>('notesExcerpt',{excerpts,bilingual,thought,clipId:capture?.id,latex:latex||undefined});onSaved(result.excerptId);onClose();}catch(e){setError(errorText(e));}finally{setBusy('');}}
  return <div className="modal-backdrop"><section className="excerpt-dialog" role="dialog" aria-label={formula?'提取公式':'加入文献笔记'}><div className="modal-title"><h2>{formula?'提取公式':'加入文献笔记'}</h2><button className="icon-button" disabled={!!busy} aria-label="关闭摘录" onClick={onClose}><X size={20}/></button></div><div className="excerpt-scroll">{capture&&<img className="capture-preview" src={'data:image/png;base64,'+capture.png} alt="选中区域的原始截图"/>}{formula&&<><p className="muted" role="status">{recognizing?<><LoaderCircle size={15} className="spin"/> 正在本地识别；首次使用需下载约 701 MB 模型…</>:recognized?'识别完成，可对照原图修改。':'识别未完成，可重试。'}</p>{!recognizing&&<button className="button secondary" disabled={!!busy} onClick={()=>setAttempt(value=>value+1)}><ScanText size={16}/>重新识别</button>}<textarea className="latex-editor" aria-label="LaTeX 公式代码" rows={4} disabled={recognizing} value={latex} onChange={e=>setLatex(e.target.value)}/><div className="formula-preview" dangerouslySetInnerHTML={{__html:preview}}/><div className="formula-actions"><button className="button secondary" disabled={!latex} onClick={()=>void copy()}><Copy size={14}/>复制 LaTeX</button><button className="button secondary" disabled={!latex} onClick={()=>void copy(true)}>复制 Markdown</button><span>{copied}</span></div></>}{!formula&&excerpts.map((e,i)=><div className="excerpt-pair" key={i}><small>第 {e.page+1} 页</small><blockquote>{e.source||'此区域没有可提取的原文。'}</blockquote>{e.translation?<blockquote lang="zh">{e.translation}</blockquote>:<p className="muted">暂无可靠对应译文，可在笔记中补充。</p>}</div>)}<label className="research-check"><input type="checkbox" checked={bilingual} onChange={e=>setBilingual(e.target.checked)}/>摘录中保留双语内容</label><label>个人想法<textarea aria-label="摘录个人想法" rows={3} value={thought} onChange={e=>setThought(e.target.value)} placeholder="记录你的理解…"/></label></div>{error&&<p className="research-error">{error}</p>}<div className="modal-actions"><span>{busy&&<><LoaderCircle size={15} className="spin"/>{busy}</>}</span><button className="button primary" disabled={!!busy||recognizing} onClick={()=>void save()}><NotebookPen size={16}/>加入笔记</button></div></section></div>;
}
