import { useEffect,useState } from 'react';
import { palettes,paletteId } from './palettes';
import { FolderOpen,X } from 'lucide-react';
import { api,errorText,type NotesConfig } from './research-types';
export function applyAppearance(){document.documentElement.dataset.palette=paletteId();document.documentElement.dataset.theme=localStorage.getItem('theme')||'light';}
export function ResearchSettings({onClose}:{onClose:()=>void}){
  const [config,setConfig]=useState<NotesConfig|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[folder,setFolder]=useState('Papers'),[migrate,setMigrate]=useState(false),[palette,setPalette]=useState(paletteId()),[mode,setMode]=useState(localStorage.getItem('theme')||'light');
  useEffect(()=>{void api<NotesConfig>('researchSettings').then(c=>{setConfig(c);setFolder(c.notesFolder);}).catch(e=>setError(errorText(e)));return window.pdfsandwich.onEvent(e=>{if(e.type==='notes-settings'&&e.settings){setConfig(e.settings);setFolder(e.settings.notesFolder);}});},[]);
  async function configure(mode:'standalone'|'obsidian',choose=false){setBusy(true);try{const result=await api<NotesConfig|null>('notesConfigure',{mode,choose,notesFolder:folder,migrate});if(result){setConfig(result);setFolder(result.notesFolder);setError('');}}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <div className="modal-backdrop"><section className="research-settings" role="dialog" aria-label="阅读与笔记设置"><div className="modal-title"><h2>阅读与笔记</h2><button className="icon-button" aria-label="关闭笔记设置" disabled={busy} onClick={onClose}><X size={20}/></button></div><h3>配色</h3><div className="palette-options">{palettes.map(p=><button key={p.id} className={palette===p.id?'active':''} onClick={()=>{setPalette(p.id);localStorage.setItem('palette',p.id);applyAppearance();window.dispatchEvent(new Event('appearance'));}}><div className="palette-art" style={Object.fromEntries(p.colors.map((c,i)=>['--p'+i,c]))}/><div className="palette-caption"><strong>{p.name}</strong><span>{p.detail}</span></div><div className="palette-swatches">{p.colors.map(c=><i key={c} style={{background:c}}/>)}</div></button>)}</div><div className="palette-mode">{(['light','dark'] as const).map(value=><button key={value} className={mode===value?'active':''} onClick={()=>{localStorage.setItem('theme',value);applyAppearance();window.dispatchEvent(new Event('appearance'));setMode(value);}}>{value==='light'?'浅色':'深色'}</button>)}</div><h3>Markdown 存储</h3><div className="mode-options"><button className={config?.mode==='standalone'?'active':''} disabled={busy} onClick={()=>void configure('standalone')}>独立 Markdown</button><button className={config?.mode==='obsidian'?'active':''} disabled={busy} onClick={()=>void configure('obsidian')}>Obsidian Vault</button></div><p className="settings-path">{config?.root||'请选择可访问的笔记目录'}</p><button className="button secondary" disabled={busy} onClick={()=>void configure(config?.mode||'standalone',true)}><FolderOpen size={16}/>{config?.mode==='obsidian'?'选择 Vault':'选择笔记文件夹'}</button>{config?.mode==='obsidian'&&<label>Vault 内的笔记文件夹<input aria-label="Vault 笔记文件夹" value={folder} onChange={e=>setFolder(e.target.value)}/><button className="button secondary" disabled={busy||folder===config.notesFolder} onClick={()=>void configure('obsidian')}>应用文件夹设置</button></label>}<label className="research-check"><input type="checkbox" checked={migrate} disabled={busy} onChange={e=>setMigrate(e.target.checked)}/>切换位置时复制当前笔记和附件</label><p className="muted">未勾选时直接使用所选目录中的笔记。复制迁移会保留原目录，并检查同名文件。</p>{config?.mode==='obsidian'&&<p className="muted">图片附件沿用 Obsidian 设置：{config.attachmentDirectory}。笔记与 Obsidian 共用 Markdown 文件。安装 PDFSandwich Companion 插件后，也可在 Obsidian 内设置此文件夹。</p>}{error&&<p className="research-error">{error}</p>}{busy&&<p>正在更新笔记位置…</p>}</section></div>;
}
